services:
  api:
    build:
      cache_from:
        - ghcr.io/sunlao/achat-api:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"  
    image: ghcr.io/sunlao/achat-api:latest
    environment:
      - PYTHONPATH=/app/src:/app
      - COVERAGE_PROCESS_START=/app/tox.ini
      - COVERAGE_FILE=/app/tests/.coverage.api
    volumes:
      - ./tox.ini:/app/tox.ini:ro
      - ./tests:/app/tests:rw

  dbt-runtime:
    build:
      cache_from:
        - ghcr.io/sunlao/achat-dbt-runtime:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"  
    image: ghcr.io/sunlao/achat-dbt-runtime:latest
    environment:
      - PYTHONPATH=/app/src:/app
      - COVERAGE_PROCESS_START=/app/tox.ini
      - COVERAGE_FILE=/app/tests/.coverage.xform      
    volumes:
      - ./tox.ini:/app/tox.ini:ro
      - ./tests:/app/tests:rw

  db-deploy:
    build:
      cache_from:
        - ghcr.io/sunlao/achat-db-deploy:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"  
    image: ghcr.io/sunlao/achat-db-deploy:latest

  postgres:
    environment:
      - ENV=ci

  redis:
    environment:
      - ENV=ci

  quiesce:
    environment:
      - ENV=ci

  worker:
    build:
      cache_from:
        - ghcr.io/sunlao/achat-worker:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"  
    image: ghcr.io/sunlao/achat-worker:latest
    entrypoint: bash -c "cd /app && python -m coverage run -m arq src.worker.AppSettings"
    environment:
      - PYTHONPATH=/app/src:/app
      - COVERAGE_PROCESS_START=/app/tox.ini
      - COVERAGE_FILE=/app/tests/.coverage.worker      
    volumes:
      - ./tox.ini:/app/tox.ini:ro
      - ./tests:/app/tests:rw

  test:
    build:
      cache_from:
        - ghcr.io/sunlao/achat-test:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: ghcr.io/sunlao/achat-test:latest
    volumes:
      - ./docs/code_coverage:/app/doc:rw
