[tox]
envlist = py311
skipsdist = True
[testenv]
description = Full local testing environment (minus code coverage)
skip_install = true
passenv =
    APP_CODE
    SERVICE
    ENV
    API_HOST
    API_PORT
    API_STATIC_DIR
    DB_APP_PWD
    DB_DATA_PWD
    XFORM_DIR
    DB_PORT
    DB_HOST
    REDIS_HOST
    REDIS_PORT
    LOG_DIR
    LOG_LEVEL
    XFORM_RUNS_DIR
    JOB_PATH
    JOB_VERSION
    GATE_CLOSE_PATH
setenv =
    PYTHONPATH=/app/tests:/app/src:
    DB_MAX_POOL=4
    DATA_DIR=/data
deps=
allowlist_externals =
    black
    pylint
    pycodestyle
    coverage
    pytest
    bandit
    pip-audit
commands =
    pip install --upgrade pip
    black src tests
    pylint --rcfile=tox.ini src
    pylint --rcfile=tox.ini --disable=C0103 tests
    pycodestyle src tests
    pytest --color=yes
    bandit -r src
    pip-audit -r requirements.txt
[testenv:po]
description = pytest only - discrete local testing wit pos args
skip_install = true
deps =
allowlist_externals = pytest
passenv =
    APP_CODE
    SERVICE
    ENV
    API_HOST
    API_PORT
    API_STATIC_DIR
    DB_APP_PWD
    DB_DATA_PWD
    XFORM_DIR
    DB_PORT
    DB_HOST
    REDIS_HOST
    REDIS_PORT
    LOG_DIR
    LOG_LEVEL
    XFORM_RUNS_DIR
    JOB_PATH
    JOB_VERSION
    GATE_CLOSE_PATH
setenv =
    PYTHONPATH=/app/tests:/app/src:
    DB_MAX_POOL=4
    DATA_DIR=/data
commands =
    pytest --color=yes {posargs}
[testenv:ci]
description = customized for CI pipeline
skip_install = true
passenv =
    APP_CODE
    SERVICE
    ENV
    API_HOST
    API_PORT
    API_STATIC_DIR
    DB_APP_PWD
    DB_DATA_PWD
    XFORM_DIR
    DB_PORT
    DB_HOST
    REDIS_HOST
    REDIS_PORT
    LOG_DIR
    LOG_LEVEL
    XFORM_RUNS_DIR
    JOB_PATH
    JOB_VERSION
    GATE_CLOSE_PATH
setenv =
    PYTHONPATH=/app/tests:/app/src:
    DB_MAX_POOL=4
    DATA_DIR=/data
allowlist_externals =
    coverage
    pytest 
    genbadge
deps =
    -rrequirements.txt
    -rrequirements-test.txt
commands=
    coverage run -m pytest --color=yes {posargs}
    python -m tests.scripts.flush_api
    python -m tests.scripts.flush_worker
    coverage combine
    coverage report
    coverage xml -o /app/doc/coverage.xml
    coverage html -d /app/doc
    genbadge coverage -i /app/doc/coverage.xml -o /app/doc/coverage.svg
[pycodestyle]
max-line-length = 90
ignore = E126, W503, W504, E203
exclude = .tox, .venv, *test_02_fp_policy_in_core*, *xtest_02_fp_policy_in_core*,
[pytest]
log_cli = 1
log_cli_level = INFO
log_cli_format = "%(asctime)s [%(levelname)8s] [%(filename)s:%(lineno)s] - %(message)s"
asyncio_mode = auto
addopts = -vxs -p no:warnings
testpaths = tests/pytest
norecursedirs = src/xform/dbt_packages
filterwarnings =
    ignore::UserWarning:genbadge.utils_badge
[coverage:run]
parallel = True
branch = True
concurrency = multiprocessing
data_file=/app/tests/.coverage
relative_files = True
disable_warnings = couldnt-parse
source = /app/src 
omit=
    */.github/*
    */.tox/*
    */.venv/*
    */data/*
    */deploy/*
    */scripts/*
    */tests/*
[coverage:paths]
source =
    /app/src
    src
    /usr/local/lib/python3.11/site-packages/pss
[coverage:report]                   
ignore_errors = True
[pylint]
ignore-paths = src/xform/dbt_packages
disable=
    # Classes should wrap more than 3 functions public and internal
    # Do not focus on public  
    too-few-public-methods,
    # Using TODO's is ok and helpful for tracking roadmap alignment
    fixme,
    # need a better docstring strategy this is probably too lazy
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,
    # rem when fully implemented
    duplicate-code, 